
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'getground'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'getground'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# on-run-end: "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}" 

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  elementary:
    +schema: 'elementary'
  getground:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +enabled: true
      +materialized: table
      +schema: staging
      +docs: 
        show: true
        node_color: "red"
    master:
      +enabled: true
      +materialized: table
      +schema: master
      +docs: 
        show: true
        node_color: "blue"
    dw:
      +enabled: true
      +materialized: table
      +schema: dw
      +docs: 
        show: true
        node_color: "green"
    mart:
      +enabled: true
      +materialized: view
      +schema: mart
      +docs: 
        show: true
        node_color: "gold"

seeds:
  getground:
    +enabled: true
    +schema: seed_data
    +quote_columns: false

tests:
  +store_failures: true
  +schema: error_data