version: 2

seeds:
  - name: partners
    config:
      column_types:
        id: INT64
        partner_type: STRING
        lead_sales_contact: STRING
        created_at: FLOAT64
        updated_at: FLOAT64

  - name: referrals
    config:
      column_types:
        id: INT64
        partner_id: INT64
        company_id: INT64
        consultant_id: INT64
        status: STRING
        is_outbound: BOOLEAN
        created_at: FLOAT64
        updated_at: FLOAT64

  - name: sales_people
    config:
      column_types:
        name: STRING
        country: STRING

      