version: 2

sources:
    

  - name: 'seed_data'
    description: "CSVs provided are dumped here."
    tables:
      - name: partners
      - name: referrals
      - name: sales_people
  
  - name: 'staging'
    description: "Staging tables"
    tables:
      - name: stg_partner
      - name: stg_referral
      - name: stg_sales_person
  
  - name: 'master'
    description: "Master tables contain entire data"
    tables:
      - name: partner
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: master_created_date
      - name: referral
      - name: sales_person
  
  - name: 'dw'
    description: "Star schema tables"
    tables:
      - name: DimPartner
      - name: DimReferral
      - name: DimSalesPerson
      - name: FactPartnerSalesPerson
      - name: FactReferralConsultant
      
  - name: 'mart'
    description: "Star schema tables"
    tables:
      - name: GetGroundDataMart
      - name: PartnerReportMart
      - name: ReferralReportMart